x = 0

try:
    print(5/x)
except ZeroDivisionError:
    print("Something went wrong")

print("I am excecuting after the try clause")

